name: measure_app
description: 手机测量器 - 屏幕尺子、AR测量、标定物测量
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^4.0.2
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
